%% Eric Morse ECE310 hw3
T = 0.004;
N= 4096;
r1 = randn(1,N);
m1 = mean(r1);
v1 = var(r1);
[counts, centers] = hist(r1, 50);
figure(1)
bar(centers, counts);
title('histogram of noise generated by randn');
ylabel('occurances');
xlabel('value');
R1= fft(r1)*T/N;
fftout = fftshift(R1);
Xft = abs(fftout).^2;
Pft = Xft/T;
deltaf = 1/T;
f = linspace(-(N/2)*deltaf, ((N/2)-1)*deltaf, N);
figure(2)
periodogram(Pft)
%No is dB/rad/sample that noise should be constant
No = 20*log(v1/(2*512000))/log(10);
[b, a] = cheby1(5, 1, 0.078125);
y = filter(b, a, r1);
m2 = mean(y);
[counts2, centers2] = hist(y, 50);
%plotting output waveform for comparison
figure(3)
subplot(2,1,1);
bar(centers, counts);
title('input histogram');
ylabel('occurances');
xlabel('value');
subplot(2,1,2);
bar(centers2, counts2);
title('output histogram');
ylabel('occurances');
xlabel('values');
%creating periodogram of output waveform
figure(4)
fft2= fft(y)*T/N;
Xft2 = abs(fft2).^2;
Yft = Xft2/T;
periodogram(Yft)
%% Problem 5
K = linspace(0, 1.08);
Pno = 0.0172;
semilogy(K, Q(sqrt(K.^2/Pno)));
title('Probability of error vs threshold plot');
ylabel('Probability of error');
xlabel('threshold level K');
xlim([0 1.08]);
ylim([10^(-17) 1]);