// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Jan 16 19:01:38 2018

dff_enrst dff_enrst_inst
(
	.D(D_sig) ,	// input  D_sig
	.EN(EN_sig) ,	// input  EN_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.PRN(PRN_sig) ,	// input  PRN_sig
	.CLRN(CLRN_sig) ,	// input  CLRN_sig
	.RSTN(RSTN_sig) ,	// input  RSTN_sig
	.Q(Q_sig) 	// output  Q_sig
);

